### PR TITLE
handle api tokens and xsrf

### LINKED ISSUE #1842: Authentication does not work with JupyterHub 4.1.2
### Bug description

I'm using the [local-binder-local-hub](https://github.com/jupyterhub/binderhub/tree/main/testing/local-binder-local-hub) setup with auth enabled (`c.BinderHub.auth_enabled = True`). This setup works well up to JupyterHub 4.0.2. 

Starting from 4.1.2,  it does not work anymore with the following errors

```bash
[I 2024-04-09 15:50:00.086 JupyterHub log:192] 200 POST /hub/api/oauth2/token (binder@10.255.255.254) 33.50ms
[D 240409 15:50:00 auth:527] HubAuth cache miss: token:76615381b56649daa983eeb0db8d467c:88eec0b396b0b2a4c89d43d6edcd220c8146120210ba068ec8f6c9231cc00ea6
[I 2024-04-09 15:50:00.101 JupyterHub log:192] 200 GET /hub/api/user (alice@10.255.255.254) 13.31ms
[D 240409 15:50:00 auth:538] Received request from Hub user {'groups': [], 'kind': 'user', 'admin': False, 'name': 'alice', 'session_id': '76615381b56649daa983eeb0db8d467c', 'scopes': ['access:services!service=binder', 'read:users:groups!user=alice', 'read:users:name!user=alice']}
[I 240409 15:50:00 auth:1527] Logged-in user {'groups': [], 'kind': 'user', 'admin': False, 'name': 'alice', 'session_id': '76615381b56649daa983eeb0db8d467c', 'scopes': ['access:services!service=binder', 'read:users:groups!user=alice', 'read:users:name!user=alice']}
[D 240409 15:50:00 auth:1195] Setting oauth cookie for 127.0.0.1: service-binderhub, {'path': '/services/binder/', 'httponly': True}
[I 240409 15:50:00 _xsrf_utils:125] Setting new xsrf cookie for b'76615381b56649daa983eeb0db8d467c:88eec0b396b0b2a4c89d43d6edcd220c8146120210ba068ec8f6c9231cc00ea6' {'path': '/services/binder/'}
[D 240409 15:50:00 auth:977] Not accepting cookie auth on GET /services/binder/oauth_callback: '_xsrf' argument missing from GET
[D 240409 15:50:00 auth:781] No user identified
```

and in the browser:

```
GET http://127.0.0.1:8000/services/binder/oauth_callback?code=RjcOLjkaqwPffgVJsEN4h6RqWOX1RF&state=eyJ1dWlkIjogIjRm...QUQifQ net::ERR_TOO_MANY_REDIRECTS
```
### How to reproduce

- Install  JupyterHub 4.1.2
- Set up `binderhub` with  [local-binder-local-hub](https://github.com/jupyterhub/binderhub/tree/main/testing/local-binder-local-hub) 
- Switch `c.JupyterHub.authenticator_class` to `DummyAuthenticator`
- Add `c.BinderHub.auth_enabled = True` to `binderhub_config.py`
- Launch any repository 

#### Expected behaviour

The builder process should start

### Your personal set up

- `binderhub` at main
- `jupyterhub` 4.1.2

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

### PR DESCRIPTION
**Pull request by minrk**
- When authenticated with JupyterHub, XSRF checks are applied to GET requests, blocking the EventSource
- switch to fetch-based EventSource implementation, since base EventSource doesn't allow headers (like websockets)
- allow api tokens for authenticated requests, which avoids auth issues including enabling cross-origin requests to authenticated servers

fixes #1842

### CODE REVIEW

File: js/packages/binderhub-client/lib/index.js [hunk 1]
```diff
@@ -14,8 +26,15 @@ export class BinderRepository {
...
    * @param {boolean} [buildOnly] Opt out of launching built image by default by passing `build_only` param
+   * @param {string} [apiToken] Optional Bearer token for authenticating requests
    */
-  constructor(providerSpec, buildEndpointUrl, buildToken, buildOnly) {
+  constructor(
+    providerSpec,
+    buildEndpointUrl,
+    buildToken,
+    buildOnly,
+    { apiToken },
```
Comment (minrk) [inline js/packages/binderhub-client/lib/index.js:36]: Start accepting keyword arguments here, which we should probably do going forward, rather than continuing to add positional arguments. I'm not sure what our API stance is on changing this, otherwise I would have collapsed buildToken and buildOnly into the `options` dict, but that's a breaking API change here.

File: binderhub/static/js/index.js [hunk 2]
```diff
@@ -61,11 +60,14 @@ async function build(providerSpec, log, fitAddon, path, pathType) {
   $(".on-build").removeClass("hidden");
 
   const buildToken = $("#build-token").data("token");
+  let apiToken = $("#api-token").data("token");
```
Comment (yuvipanda) [inline binderhub/static/js/index.js:63]:
```suggestion
  const apiToken = $("#api-token").data("token");
```

File: js/packages/binderhub-client/lib/index.js (hunk 1 above)
Comment (yuvipanda) [reply js/packages/binderhub-client/lib/index.js:36]: @minrk agree re: keyword arguments. https://github.com/yuvipanda/jupyterhub-fancy-profiles is the only current user of this external to this repo, so I think you should just make the breaking change right now.

File: js/packages/binderhub-client/lib/index.js [hunk 3]
```diff
@@ -1,9 +1,21 @@
...
+function _getXSRFToken() {
+  // from @jupyterlab/services
+  let cookie = "";
+  try {
+    cookie = document.cookie;
+  } catch (e) {
+    // e.g. SecurityError in case of CSP Sandbox
+    return null;
+  }
+  const xsrfTokenMatch = cookie.match("\\b_xsrf=([^;]*)\\b");
```
Comment (yuvipanda) [inline js/packages/binderhub-client/lib/index.js:13]: regexes in anything security sensitive always make me nervous haha. Can you either add a comment here explaining what's going on, or a direct link to the specific place from @jupyterlab/services this was stolen from?

**Comment by yuvipanda** [comment]
I think we can make the breaking change for how params are passed now! And with the tests fixed, I think this is good to go.

**Comment by minrk** [comment]
I have it working locally, but I've spent my whole day so far trying to get the tests to accurately describe that the coe is working, but they keep failing with unhandled errors that should be handled as regular close events.

File: js/packages/binderhub-client/lib/index.js (hunk 3 above)
Comment (minrk) [reply js/packages/binderhub-client/lib/index.js:13]: added link and explanation. It's still astonishing to me that there is no API for geting cookies by name in browsers, but it is `{name}={anything but a semicolon}[; again]`

**Review by manics — COMMENTED** [review]
Tested successfully with https://github.com/jupyterhub/binderhub/pull/1851

Other than a typo this looks good to me

**Comment by yuvipanda** [comment]
Thanks for testing, @manics.

**Comment by yuvipanda** [comment]
I deployed this to mybinder.org too, and it seems ok.

**Comment by minrk** [comment]
Thanks for finishing this!
